### PR TITLE
Fix show instances for unused type variables

### PR DESCRIPTION
**Pull request by flip111**
Still has problems with enum and ord, but show should be fixed now.

### CODE REVIEW

**Comment by flip111** [comment]
https://github.com/eskimor/purescript-bridge/pull/89

**Comment by flip111** [comment]
I changed some config files from old spago to new spago. Not sure if you want to migrate or keep with old spago. In case you want to keep old spago then just take the changed code

**Comment by peterbecich** [comment]
Thanks for this PR
With/without this change, there is some issue with the new Spago I have not figured out yet. I have moved the Spago upgrade to a different PR, excluding this change to `Show`, to look into that: https://github.com/peterbecich/purescript-bridge/pull/2

**Comment by peterbecich** [comment]
@flip111, please take a look at this error. I believe it is reproducible with `stack test` or `cabal test` in the root of the project, or in the "Haskell Library and Example" GitHub Action:

```
purescript-bridge>        [1/1 CycleInDeclaration] src/RoundTripJsonHelpers/Types.purs:197:1
purescript-bridge>             
purescript-bridge>               v
purescript-bridge>          197  instance Show TestRecursiveB where
purescript-bridge>          198    show = genericShow
purescript-bridge>                                  ^
purescript-bridge>             
purescript-bridge>          The value of $showTestRecursiveB94 is undefined here, so this reference is not allowed.
purescript-bridge>             
```

The test generates `test/RoundTripJsonHelpers/app/src/RoundTripJsonHelpers/Types.purs`. This `instance` specifically is the issue:
https://github.com/flip111/purescript-bridge/blob/8c389d1bf8ae66147d66fdefbd4f8b7c873b1c09/test/RoundTripJsonHelpers/app/src/RoundTripJsonHelpers/Types.purs#L197-L198

I have not scrutinized the error carefully and it may be easier to solve than I think. It doesn't occur on the upstream branch.


-----

I have upstreamed the Spago upgrade and re-based this branch `fix-show2` to reduce the PR.


----

Thanks again

**Comment by flip111** [comment]
Is the new commit part of a branch? Which branch? https://github.com/peterbecich/purescript-bridge/commit/8c389d1bf8ae66147d66fdefbd4f8b7c873b1c09

**Comment by flip111** [comment]
The problem is a purescript specific thing which could be regarded as either a purescript compiler bug or a missing purescript compiler feature. Described here https://github.com/purescript/documentation/blob/master/errors/CycleInDeclaration.md It also describes a fix (eta expanding). Long story short i will put that variable back and then it should be good to go.

https://wiki.haskell.org/Eta_conversion

**Comment by peterbecich** [comment]
fantastic, thanks @flip111

**Pull request merged**
